### ISSUE TITLE
kSleighSpecInstallDir filled in with relative path

### ISSUE THREAD

**Issue by 2over12** [lifting-bits/sleigh#124]
In remill builds on latest sleigh (74838a39ba7ddd91becb1d7f59e6cc3d7e3956de) the value for the sleighspecinstalldir is `static const char *kSleighSpecInstallDir = "share/sleigh/specfiles";`. This value causes searching for sla files to fail when the build directory has been deleted, which occurs in the Dockerfile for remill

**Comment by ekilmer** [comment]
The relative path is intentional. There's no way to know where the base install directory is located and hard-coding isn't correct due to the possibility of relocatable installations.

What we could do is add another constant `kSleighBaseInstallDir`, which would be set to `CMAKE_INSTALL_PREFIX` and then you could combine the two to get something that should work if the installation directory wasn't relocated. However, if you plan to use a package manager like vcpkg, then `kSleighBaseInstallDir` won't be valid because vcpkg installations are relocatable.

Another option would be to use the `PACKAGE_PREFIX_DIR` CMake variable _after_ the call to `find_package(sleigh REQUIRED COMPONENTS Support Specs)`. This variable should be saved to a variable like `<project>_sleigh_install_prefix`, and it will have the value of the base installation directory with which you can do something.
